In [1]:
import numpy as np

arr = np.ones((3, 3), dtype=bool)

print(arr)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [2]:
import numpy as np

arr = np.linspace(5, 50, 10)

print(arr)

[ 5. 10. 15. 20. 25. 30. 35. 40. 45. 50.]


In [3]:
import numpy as np

my_list = [10, 20, 30, 40, 50]

arr = np.array(my_list)

print(arr)

[10 20 30 40 50]


In [4]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

reversed_arr = arr[::-1]

print(reversed_arr)

[5 4 3 2 1]


In [5]:
import numpy as np

matrix = np.eye(3)

print(matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [6]:
import numpy as np

arr = np.arange(1, 17).reshape(4, 4)

first_row = arr[0, :]
last_column = arr[:, -1]

print("Array:")
print(arr)

print("First row:")
print(first_row)

print("Last column:")
print(last_column)

Array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
First row:
[1 2 3 4]
Last column:
[ 4  8 12 16]


In [7]:
import numpy as np

arr = np.arange(1, 17).reshape(4, 4)

result = arr[:2, :2]

print(result)

[[1 2]
 [5 6]]


In [8]:
import numpy as np

a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

print("Addition:", a + b)
print("Subtraction:", a - b)
print("Multiplication:", a * b)
print("Division:", a / b)

Addition: [ 6  8 10 12]
Subtraction: [-4 -4 -4 -4]
Multiplication: [ 5 12 21 32]
Division: [0.2        0.33333333 0.42857143 0.5       ]


In [9]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

dot_product = np.dot(a, b)

print(dot_product)

32


In [10]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

mean = np.mean(arr)
median = np.median(arr)
std = np.std(arr)

print("Mean:", mean)
print("Median:", median)
print("Standard deviation:", std)

Mean: 30.0
Median: 30.0
Standard deviation: 14.142135623730951
